% Default figure properties
set(0, 'DefaultFigureColor', 0.05*ones(1,3), ...
'DefaultFigurePaperType', 'a4letter', ...
'DefaultAxesColor', 0.05*ones(1,3), ...
'DefaultAxesDrawmode', 'fast', ...
'DefaultAxesFontUnits', 'points',...
'DefaultAxesFontSize', 16, ...
'DefaultAxesFontAngle', 'Normal', ...
'DefaultAxesFontName', 'Tahoma', ...
'DefaultAxesFontWeight', 'Bold', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesInterruptible', 'on', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesNextPlot', 'replace',...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', 0.9*ones(1,3), ...
'DefaultAxesYcolor', 0.9*ones(1,3), ...
'DefaultAxesZcolor', 0.9*ones(1,3), ...
'DefaultAxesVisible', 'on', ...
'DefaultLineColor', 'r', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 2, ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 10, ...
'DefaultTextColor', 0.9*ones(1,3), ...
'DefaultTextFontUnits', 'Points',...
'DefaultTextFontSize', 16, ...
'DefaultTextFontName', 'Georgia', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultAxesColorOrder', 0.7*flipud(varycolor(5)) + 0.3*rand(5,3), ...
'DefaultTextHorizontalAlignment', 'left');
