% Default figure properties
set(0, 'DefaultFigureColor', [1 1 1], ...
'DefaultFigurePaperType', 'a4letter', ...
'DefaultAxesColor', [1 1 1], ...
'DefaultAxesDrawmode', 'fast', ...
'DefaultAxesFontUnits', 'points',...
'DefaultAxesFontSize', 16, ...
'DefaultAxesFontAngle', 'Normal', ...
'DefaultAxesFontName', 'Geneva', ...
'DefaultAxesFontWeight', 'Bold', ...
'DefaultAxesGridLineStyle', ':', ...
'DefaultAxesInterruptible', 'on', ...
'DefaultAxesLayer', 'Bottom', ...
'DefaultAxesNextPlot', 'replace',...
'DefaultAxesUnits', 'normalized', ...
'DefaultAxesXcolor', [0.1, 0.1, 0.1], ...
'DefaultAxesYcolor', [0.1, 0.1, 0.1], ...
'DefaultAxesZcolor', [0.1, 0.1, 0.1], ...
'DefaultAxesVisible', 'on', ...
'DefaultLineColor', 'r', ...
'DefaultLineLineStyle', '-', ...
'DefaultLineLineWidth', 2, ...
'DefaultLineMarker', 'none', ...
'DefaultLineMarkerSize', 10, ...
'DefaultTextColor', [0.2, 0.2, 0.2], ...
'DefaultTextFontUnits', 'Points',...
'DefaultTextFontSize', 16, ...
'DefaultTextFontName', 'Geneva', ...
'DefaultTextVerticalAlignment', 'middle', ...
'DefaultAxesColorOrder', 0.7*flipud(varycolor(5)) + 0.3*rand(5,3), ...
'DefaultTextHorizontalAlignment', 'left');
